---
sudo: required
language: python
os: linux
dist: bionic
services:
  - docker
install:
  - python3 -m pip install ansible
  - python3 -m pip install molecule
  - python3 -m pip install molecule-docker
script:
  - molecule converge -s centos
  - molecule converge -s ubuntu
  - molecule converge -s fedora
