---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: docker-ce-role-fedora
    image: docker.io/pycontribs/fedora:latest
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
scenario:
  name: fedora
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # Skip this to use dnf config-manager
    # - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint
  flake8
