---
- name: "Gather packages information"
  package_facts:

- name: "Ensure Docker version is correct"
  fail:
    msg: "Something went wrong with the installation, Docker version is not {{ docker.version }}"
  when: docker.version != ansible_facts.packages.docker.version
