---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: docker-ce-role-centos
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: centos
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # Skip this to use yum-config-manager
    # - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint
  flake8
