---
- name: "Uninstall old versions of Docker"
  yum:
    name: "{{ item }}"
    state: absent
  become: true
  loop:
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine

- name: "Install yum-utils"
  yum:
    name: "yum-utils"
    state: present
  become: true

- name: "Import docker-ce repository"
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: true

- name: "Update yum"
  yum:
    name: "*"
    state: latest
    exclude:
    - docker-ce
    - docker-ce-cli
  become: true

- name: "Install docker components"
  yum:
    name: "{{ item }}"
    state: present
    allow_downgrade: yes
  become: true
  loop:
  - "docker-ce{% if docker.version is defined %}-{{ docker.version }}{% endif %}"
  - "docker-ce-cli{% if docker.version is defined %}-{{ docker.version }}{% endif %}"
  - containerd.io
  notify: "Start docker"
