---
- name: "Uninstall old versions of Docker"
  dnf:
    name: "{{ item }}"
    state: absent
  become: true
  loop:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-selinux
  - docker-engine-selinux
  - docker-engine

- name: "Install Docker for Fedora < 33"
  when: ansible_distribution_version < '33'
  block:
  - name: "Install the dnf-plugins-core package"
    dnf:
      name: "dnf-plugins-core"
      state: latest
    become: true

  - name: "set up the stable repository"
    shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    become: true

  - name: "Install docker components"
    dnf:
      name: "{{ item }}"
      state: latest
    become: true
    loop:
    - "docker-ce{% if docker.version is defined %}-{{ docker.version }}{% endif %}"
    - "docker-ce-cli{% if docker.version is defined %}-{{ docker.version }}{% endif %}"
    - containerd.io

- name: "Install Docker for Fedora 33"
  when: ansible_distribution_version == '33'
  block:
  - name: "Install docker components"
    dnf:
      name: "{{ item }}"
      state: present
    become: true
    loop:
    - "moby-engine{% if docker.version is defined %}-{{ docker.version }}{% endif %}"
    - "docker-compose{% if docker.version is defined %}-{{ docker.version }}{% endif %}"

- name: "Enable the backward compatibility for Cgroups"
  lineinfile:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX="rhgb quiet"'
    line: 'GRUB_CMDLINE_LINUX="rhgb quiet systemd.unified_cgroup_hierarchy=0"'
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution_version >= '31'
  ignore_errors: true
  become: true

- name: "Reboot to take changes"
  reboot:
  become: true

- name: "Wait for host to be ready"
  wait_for:
    port: 22
  notify: "Start docker"
