---
- name: "Start docker"
  systemd:
    name: docker
    enabled: true
    state: started
  become: true

- name: "Start docker service"
  service:
    name: docker
    enabled: true
    state: started
  become: true
