---
- name: "End the play for hosts that do not run CentOS or RHEL"
  meta: end_host
  when:
  - ansible_distribution != 'Fedora' and (ansible_distribution_major_version != "30" or ansible_distribution_major_version != "31")
