---
- name: "End the play for hosts that do not run CentOS or RHEL"
  meta: end_host
  when:
  - ansible_distribution != 'Ubuntu' and (ansible_distribution_release != "Focal" or ansible_distribution_release != "Bionic" or ansible_distribution_release != "Xenial")
