---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: docker-ce-role
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
privileged: true
