---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: docker-ce-role-ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    privileged: true
provisioner:
  name: ansible
  # env: 
  #   MOLECULE_NO_LOG: false
scenario:
  name: ubuntu
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint
  flake8
