---
name: Molecule Test

on: 
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: 
        - 3.6

    steps:

      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Docker
        run: |
          sudo apt-get remove docker docker-engine docker.io containerd runc
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Install dependencies
        run: |
          python3 -m pip install docker
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible
          python3 -m pip install molecule
          python3 -m pip install molecule-docker

      - name: Setup git credentials
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: Test with molecule on Centos 7
        run: |
          molecule converge -s centos
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: Test with molecule on Ubuntu
        run: |
          molecule converge -s ubuntu
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: Test with molecule on Fedora
        run: |
          molecule converge -s fedora
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
